---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel-roxagent-vm
  namespace: default
  labels:
    app: rhacs-scanning
    os: rhel9
  annotations:
    description: "RHEL VM with RHACS roxagent for vulnerability scanning"
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: rhel-roxagent-vm
        app: rhacs-scanning
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          # Enable vsock for RHACS communication
          autoattachVSOCK: true
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 4Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          # Option 1: Use DataVolume for RHEL image
          dataVolume:
            name: rhel9-base
        # Option 2: Use PVC with pre-uploaded RHEL image
        #  persistentVolumeClaim:
        #    claimName: rhel9-rootdisk
        # Option 3: Use containerDisk
        #  containerDisk:
        #    image: registry.redhat.io/rhel9/rhel-guest-image:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            # Reference to ConfigMap containing cloud-init
            secretRef:
              name: rhel-roxagent-cloudinit
---
apiVersion: v1
kind: Secret
metadata:
  name: rhel-roxagent-cloudinit
  namespace: default
type: Opaque
stringData:
  userdata: |
    #cloud-config
    hostname: rhel-roxagent-vm
    
    users:
      - default
      - name: rhacs
        groups: sudo
        shell: /bin/bash
        sudo: ['ALL=(ALL) NOPASSWD:ALL']
        lock_passwd: false
    
    packages:
      - curl
      - wget
      - systemd
    
    runcmd:
      # Download roxagent binary
      - mkdir -p /opt/roxagent
      - curl -L -o /opt/roxagent/roxagent https://mirror.openshift.com/pub/rhacs/assets/4.9.2/bin/linux/roxagent
      - chmod +x /opt/roxagent/roxagent
      
      # Create systemd service
      - |
        cat > /etc/systemd/system/roxagent.service <<'EOF'
        [Unit]
        Description=RHACS Virtual Machine Vulnerability Agent
        After=network-online.target
        Wants=network-online.target
        
        [Service]
        Type=simple
        ExecStart=/opt/roxagent/roxagent --daemon --index-interval=5m --verbose
        Restart=always
        RestartSec=10
        User=root
        StandardOutput=journal
        StandardError=journal
        Environment="ROX_VIRTUAL_MACHINES_VSOCK_PORT=818"
        Environment="ROX_VIRTUAL_MACHINES_VSOCK_CONN_MAX_SIZE_KB=16384"
        
        [Install]
        WantedBy=multi-user.target
        EOF
      
      # Enable and start service
      - systemctl daemon-reload
      - systemctl enable roxagent.service
      - systemctl start roxagent.service
    
    write_files:
      - path: /etc/profile.d/roxagent.sh
        permissions: '0644'
        content: |
          export ROX_VIRTUAL_MACHINES_VSOCK_PORT=818
          export ROX_VIRTUAL_MACHINES_VSOCK_CONN_MAX_SIZE_KB=16384
      
      - path: /usr/local/bin/roxagent-scan
        permissions: '0755'
        content: |
          #!/bin/bash
          /opt/roxagent/roxagent --verbose
    
    final_message: "RHACS roxagent VM ready!"
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: rhel9-base
  namespace: default
spec:
  source:
    # Option 1: Import from registry
    registry:
      url: "docker://registry.redhat.io/rhel9/rhel-guest-image:latest"
      pullMethod: node
    # Option 2: Import from HTTP
    # http:
    #   url: "https://your-server.com/rhel9.qcow2"
    # Option 3: Use PVC as source
    # pvc:
    #   namespace: source-namespace
    #   name: source-pvc
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
    storageClassName: ocs-storagecluster-ceph-rbd
