[[labname]]

= {lab_name}

Run the following to ensure your ACS environment is up to date.

*Procedure*

[start=1]
. Switch to the *Bastion* tab, located on the right side of the screen.
. Run the following
+
[source,sh,subs="attributes",role=execute]
----
git clone 
----

. Verify the deployment
+
[source,sh,role=execute]
----
----
+
.**OUTPUT**
[source,sh]
----

----
+

=== OpenShift Console Access

The Red Hat Advanced Cluster Management for Kubernetes (RHACM) Console is now integrated with OpenShift Console. To access it, select *Fleet Management* from the dropdown menu on the left once you log in.

Switch to the *OpenShift Console* tab in the right panel. In case you want to open it in another window it is here: {openshift_cluster_console_url}[window=blank]

NOTE: ctrl + click on the URL to open URLs in a new tab.

Administrator login credentials:

[cols="1,1"]
|===
| *Username:* | {openshift_cluster_admin_username}
| *Password:* | {openshift_cluster_admin_password}
|===

=== RHACS Console Access

Your RHACS Console is also available in the right panel. In case you want to open it in another window it is here: {acs_route}[window=blank]

Administrator login credentials:

[cols="1,1"]
|===
| *RHACS Console Username:* | {acs_portal_username}
| *RHACS Console Password:* | {acs_portal_password}
|===

[[whats-next]]
== What's Next