[[labname]]

= {lab_name}

== Setup Instructions (5 minutes)

To ensure your RHACS environment is up to date, and has all of the necessary components, run the following command in the *Bastion* tab.

*Procedure*

[start=1]
. Switch to the *Bastion* tab, located on the right side of the screen.
. Run the following
+
[source,sh,subs="attributes",role=execute]
----
if [ -f install.sh ]; then git pull && ./install.sh; elif [ -d rhacs-demo ]; then cd rhacs-demo && git pull && ./install.sh; else git clone https://github.com/mfosterrox/rhacs-demo.git && cd rhacs-demo && ./install.sh - {acs_portal_password}; fi
----

. Verify the deployment completed successfully
+
.**OUTPUT**
[source,sh]
----

----
+

== Access Your Consoles

=== OpenShift Console

Access the OpenShift Console from the *OpenShift Console* tab in the right panel, or open it directly: {openshift_cluster_console_url}[window=blank]

[cols="1,1"]
|===
| *Username:* | {openshift_cluster_admin_username}
| *Password:* | {openshift_cluster_admin_password}
|===

=== RHACS Console

Access the RHACS Console from the *RHACS Console* tab in the right panel, or open it directly: {acs_route}[window=blank]

[cols="1,1"]
|===
| *Username:* | {acs_portal_username}
| *Password:* | {acs_portal_password}
|===
