apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hi-python-demo
  namespace: hummingbird-demo
  labels:
    app.kubernetes.io/part-of: rhacs-demo
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      buildArgs:
        - name: HI_PYTHON_TAG
          value: "3.13"
  output:
    to:
      kind: ImageStreamTag
      name: hi-python-demo:latest
  triggers: []
