apiVersion: apps/v1
kind: Deployment
metadata:
  name: hi-python-layered
  namespace: hummingbird-demo
  labels:
    app: hi-python-layered
    demo: hummingbird-layered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hi-python-layered
  template:
    metadata:
      labels:
        app: hi-python-layered
        demo: hummingbird-layered
    spec:
      containers:
        - name: app
          image: image-registry.openshift-image-registry.svc:5000/hummingbird-demo/hi-python-demo:latest
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
