apiVersion: observability.openshift.io/v1alpha2
kind: UIPlugin
metadata:
  annotations:
    observability.openshift.io/api-support: GeneralAvailability
  name: monitoring
spec:
  monitoring:
    perses:
      enabled: true
  type: Monitoring